Repository racedisparityaudit/ethnicity-facts-and-figures-publisher, pull requests merged in 2020-02, with the labels that each got.

#1225 Fix DAC Ambiguous-buttons-issue2
  Dockerfile
  application/src/js/all/_sortable_table.js
  application/src/sass/application.scss
  application/src/sass/components/_sr_only.scss
  application/templates/cms/create_table.html
  application/templates/static_site/_table.html
  docker/README.md
  docker/requirements.txt
Labels: Accessibility

#1227 Change copy of style guide link
  application/templates/_shared/_footer.html
Labels: enhancement

#1226 Display conditional back link on save action
  application/src/js/chartbuilder/chartbuilder.js
  application/src/js/tablebuilder/tablebuilder.js
  application/templates/_shared/_breadcrumb.html
  application/templates/base.html
  application/templates/cms/create_chart.html
  application/templates/cms/create_table.html
Labels: enhancement

#1228 Add sr_only style, add colgroup tags
  application/src/sass/application.scss
  application/src/sass/components/_sr_only.scss
  application/templates/security/login_user.html
  application/templates/static_site/_table.html
Labels: bugfix, enhancement

#1230 Content changes to publisher from style guide
  application/cms/forms.py
  application/templates/cms/create_chart.html
  application/templates/cms/create_table.html
  application/templates/cms/create_upload.html
  application/templates/cms/edit_dimension.html
  application/templates/cms/edit_measure_version.html
  application/templates/forms/extended_hints/_dimension_summary.html
  application/templates/forms/extended_hints/_methodology.html
  application/templates/forms/extended_hints/_summary.html
  application/templates/forms/extended_hints/_suppression_and_disclosure.html
  application/templates/forms/extended_hints/_time_period_covered.html
Labels: enhancement

#1234 Improve password complexity rules
  application/auth/views.py
  application/register/views.py
  requirements.txt
  tests/application/admin/test_views.py
  tests/application/register/test_views.py
Labels: dependencies, enhancement, python

#1236 Add Microsoft variant of UTF-8 for csv
  .pre-commit-config.yaml
  application/cms/upload_service.py
Labels: bugfix, python

#1237 Fix chart size and label position
  application/templates/dashboards/graphs.html
  application/templates/dashboards/publications.html
Labels: Small, bugfix, python

#1238 Install and test Highcharts accessibility module
  application/src/js/charts/rd-graph.js
  application/src/js/charts/vendor/highcharts/v5/accessibility.js
  application/src/js/charts/vendor/highcharts/v5/export-data.js
  application/src/js/charts/vendor/highcharts/v5/exporting.js
  application/src/js/charts/vendor/highcharts/v5/highcharts.js
  application/src/js/charts/vendor/highcharts/v8/accessibility.js
  application/src/js/charts/vendor/highcharts/v8/export-data.js
  application/src/js/charts/vendor/highcharts/v8/exporting.js
  application/src/js/charts/vendor/highcharts/v8/highcharts.js
  gulpfile.js
Labels: Accessibility, enhancement

#1239 Fix contrast ratio on legends
  application/src/js/charts/rd-graph.js
Labels: Accessibility
