Repository racedisparityaudit/ethnicity-facts-and-figures-publisher, pull requests merged in 2020-08, with the labels that each got.

#1319 Fix accessibility issue with inc abbreviations
  application/src/js/charts/rd-graph.js
  application/templates/static_site/_table.html
  tests/functional/test_chart_builder.py
Labels: Accessibility

#1321 Fix static pages build to use new template
  application/review/views.py
  application/sitebuilder/build.py
Labels: bugfix

#1322 Fix abbreviations on ethnic groups
  application/src/js/charts/rd-graph.js
  application/templates/dashboards/ethnic_group.html
  application/templates/dashboards/ethnic_groups.html
  tests/functional/test_chart_builder.py
Labels: Accessibility, bugfix

#1320 Create newsletter.html
  application/factory.py
  application/static_site/views.py
  application/templates/_shared/_footer.html
  application/templates/static_site/static_pages/newsletter.html
  application/templates/static_site/static_pages/privacy-policy.html
  application/templates/static_site/topic.html
Labels: Accessibility, enhancement

#1323 Fix search results
  application/factory.py
Labels: bugfix

#1324 Add another case bar chart panels
  application/src/js/charts/rd-graph.js
Labels: enhancement
