Repository racedisparityaudit/ethnicity-facts-and-figures-publisher, pull requests merged in 2020-09, with the labels that each got.

#1325 Fix remaining accessibility issues
  application/cms/markdown.py
  application/cms/utils.py
  application/src/js/chartbuilder/chartbuilder.js
  application/src/js/tablebuilder/tablebuilder.js
  application/templates/cms/_custom_classification.html
  application/templates/cms/create_chart.html
  application/templates/cms/create_table.html
  application/templates/cms/edit_measure_version.html
  tests/application/cms/test_utils.py
Labels: Accessibility

#1326 Fix pdf static links
  application/cms/markdown.py
  application/templates/static_site/static_pages/style_guide/a_z.html
  application/templates/static_site/static_pages/style_guide/ethnic_groups.html
  application/templates/static_site/static_pages/summaries/public_sector_workforces.html
Labels: Accessibility

#1328 Fix pdf links copy
  application/cms/markdown.py
  application/templates/static_site/static_pages/style_guide/a_z.html
  application/templates/static_site/static_pages/style_guide/ethnic_groups.html
  application/templates/static_site/static_pages/summaries/public_sector_workforces.html
Labels: Accessibility

#1327 Fix scanner url
  application/cms/scanner_service.py
  application/cms/upload_service.py
  tests/application/cms/test_scanner_service.py
Labels: bugfix

#1330 Add tag manager
  application/templates/base.html
Labels: enhancement

#1329 new Covid 19 page
  application/static_site/views.py
  application/templates/static_site/index.html
  application/templates/static_site/static_pages/covid-19.html
  application/templates/static_site/static_pages/newsletter.html
  tests/application/static_site/test_views.py
Labels: enhancement

#1332 Create blog-posts
  application/static_site/views.py
  application/templates/_shared/_footer.html
  application/templates/static_site/static_pages/accessibility-statement.html
  application/templates/static_site/static_pages/blog-posts.html
  application/templates/static_site/static_pages/newsletter.html
  application/templates/static_site/static_pages/understanding_our_data/how_to_read_survey_data.html
  application/templates/static_site/static_pages/understanding_our_data/interpreting_our_data.html
Labels: enhancement
